
services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: