from pydantic import BaseModel, Field
from datetime import datetime
from app.enums.Role import Role

class ChatMessage(BaseModel):
    """ChatMessage is agent's chat message model"""
    role: str = Field(..., description="The role of the author's message, e.g., 'users' or 'assistant'.")
    content: str = Field(..., description="The content of the message.")

class ChatCompletionRequest(BaseModel):
    """ChatCompletionRequest is agent's request model"""
    model: str = Field(..., description="The model to use for the chats completion.")
    messages: list[ChatMessage] = Field(..., description="A list of messages in the chats conversation.")
    max_tokens: int = Field(150, description="The maximum number of tokens to generate in the response.")

class ChatCompletionResponse(BaseModel):
    """ChatCompletionResponse is agent's response model"""
    id: str = Field(..., description="The unique identifier for the chats completion request.")
    object: str = Field(..., description="The type of object returned, e.g., 'chats.completion'.")
    created: int = Field(..., description="The timestamp when the chats completion was created.")
    model: str = Field(..., description="The model used for the chats completion.")
    choices: list[ChatMessage] = Field(..., description="A list of choices generated by the model in response to the input messages.")

class MessageRequest(BaseModel):
    """MessageRequest is model for updating chat_messages"""
    role: Role
    content: str

class MessageResponse(BaseModel):
    """MessageResponse is model for chat_messages in ChatResponse"""
    id: int
    role: Role
    content: str
    created_at: datetime

    class Config:
        orm_mode = True
        from_attributes = True

class ChatRequest(BaseModel):
    """ChatRequest is model sent to api"""
    user_id: int
    title: str
    description: str

class ChatResponse(BaseModel):
    """ChatResponse is model sent from api"""
    id: int
    user: str
    title: str
    description: str
    chat_messages: list[MessageResponse]