"""user's is_active field changed to boolean from int

Revision ID: 04ddfa807254
Revises: 5d2e974e7aa5
Create Date: 2025-08-05 19:22:53.310360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04ddfa807254'
down_revision: Union[str, Sequence[str], None] = '5d2e974e7aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE users ALTER COLUMN is_active TYPE BOOLEAN USING is_active::boolean"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
