"""Chat model extended, ChatMessage timestamp added

Revision ID: 44ab4db3b651
Revises: 824a7dc72d93
Create Date: 2025-08-06 20:13:43.942305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44ab4db3b651'
down_revision: Union[str, Sequence[str], None] = '824a7dc72d93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('chats', sa.Column('title', sa.String(length=50), nullable=False))
    op.add_column('chats', sa.Column('description', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'description')
    op.drop_column('chats', 'title')
    op.alter_column('chat_messages', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=None,
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
