"""rename of due_date field to due_to, forcing server_default func.now() for created_at field in project and task tables

Revision ID: 824a7dc72d93
Revises: 668caee252a1
Create Date: 2025-08-06 13:40:18.639804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '824a7dc72d93'
down_revision: Union[str, Sequence[str], None] = '668caee252a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('due_to', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('tasks', 'due_date')
    op.alter_column('projects', 'created_at',
        server_default=sa.text('now()'),
        existing_type=sa.DateTime(timezone=True),
        nullable=False
    )
    op.alter_column('tasks', 'created_at',
        server_default=sa.text('now()'),
        existing_type=sa.DateTime(timezone=True),
        nullable=False
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('due_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'due_to')
    op.alter_column('projects', 'created_at',
        server_default=None,
        existing_type=sa.DateTime(timezone=True),
        nullable=False
    )
    op.alter_column('tasks', 'created_at',
        server_default=None,
        existing_type=sa.DateTime(timezone=True),
        nullable=False
    )
    # ### end Alembic commands ###
